language: python
sudo: false
env:
  - DJANGO="Django>=1.8.0,<1.9.0"
  - DJANGO="Django>=1.9.0,<1.10.0"

python:
  - 3.5
  - 3.4
  - 2.7

install:
  - pip install --upgrade pip setuptools pytest
  - pip install $DJANGO
  - pip install .

script: python runtests.py