language: python
sudo: false
env:
  - DJANGO="Django>=1.0.0,<1.1.0"
  - DJANGO="Django>=1.1.0,<1.2.0"
  - DJANGO="Django>=1.2.0,<1.3.0"
  - DJANGO="Django>=1.3.0,<1.4.0"
  - DJANGO="Django>=1.4.0,<1.5.0"
  - DJANGO="Django>=1.5.0,<1.6.0"
  - DJANGO="Django>=1.6.0,<1.7.0"
  - DJANGO="Django>=1.7.0,<1.8.0"
  - DJANGO="Django>=1.8.0,<1.9.0"
  - DJANGO="Django>=1.9.0,<1.10.0"

python:
  - 3.5
  - 3.4
  - 3.3
  - 3.2
  - 2.7

install:
  - pip install --upgrade pip setuptools pytest
  - pip install $DJANGO
  - pip install .

script: python runtests.py